baseURL = 'https://ritkonsult.net/'
languageCode = 'sv'
DefaultContentLanguage = 'sv'
title = 'Ritkonsult'
theme = 'ritkonsult-theme' 
copyright = 'Copyright © :YEAR: Ritkonsult'
pluralizeListTitles = false
sectionPagesMenu = 'main'
disableKinds = ["taxonomy"]
[params]
    tel = '0522-829 98' 
    email = 'info@ritkonsult.se'
    adress = 'Ritkonsult <br> Järnvägsgatan 15 <br> 331 37 Värnamo <br> Sweden'
    og_image = 'image_here'
    manifest_background = '#e8eae1'
    manifest_theme_color = '#9dab5f'
[markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
    block = true
[outputFormats]
    [outputFormats.printFormat]
        name = 'print'
        mediaType = 'text/html'
        baseName = 'print'
        isPlainText = false
    [outputFormats.webmanifest]
        name = 'site'
        mediaType = 'application/manifest+json'
        baseName = 'site'
        isPlainText = true
[languages]
    [languages.sv]
        contentDir = 'content/sv'
        languageName = 'Svenska'
        weight = 10
        [languages.sv.params]
            adress = 'Ritkonsult <br> Järnvägsgatan 15 <br> 331 37 Värnamo'
    [languages.en]
        contentDir = 'content/en'
        languageCode = 'en'
        languageName = 'English'
        weight = 20
        [languages.en.params]
            tel = '+46 522-829 98'

    [[menu.forms]]
        name = 'Insatsplan'
        url = '/blanketter/Insatsplan'
        weight = '10'
    [[menu.forms]]
        name = 'Kontrollritning'
        url = '/blanketter/kontrollritning'
        weight = '10'
    [[menu.forms]]
        name = 'Utrymningsplan'
        url = '/blanketter/utrymningsplan'
        weight = '30'

    [[menu.guides]]
        name = 'Insatsplan'
        url = '/guider/Insatsplan'
        weight = '10'
    [[menu.guides]]
        name = 'Kontrollritning'
        url = '/guider/kontrollritning'
        weight = '10'
    [[menu.guides]]
        name = 'Utrymningsplan'
        url = '/guider/utrymningsplan'
        weight = '30'